name: wrangler-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona=1.10.1
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=1.0.1
  - ijson=3.3.0
  - ipywidgets=7.8.4
  - osmnx=1.9.3
  - pandas=2.2.3
  - pandera-geopandas=0.18.0
  - psutil=6.0.0
  - pyarrow=17.0.0
  - pydantic=2.9.2
  - pyogrio=0.9.0
  - pyyaml=6.0.2
  - folium=0.17.0
  - notebook=7.2.2
  - coverage=7.6.1
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - pre-commit=4.0.1
  - pytest=8.2.2
  - pytest-benchmark=4.0.0
  - pytest-cov=5.0.0
  - pytest-profiling=1.7.0
  - ruff=0.6.8
  - snakeviz=2.2
  - markdown=3.3.7
  - typing-extensions=4.12.2
  - pip
  - python==3.10.15

  # Pip-installed dependencies
  - pip:
      - fontawesome_markdown==0.2.6
      - mike==2.1.3
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.2.0
      - mkdocs-awesome-pages-plugin==2.9.3
      - mkdocs-jupyter==0.25.0
      - mkdocs-include-markdown-plugin==6.2.2
      - mkdocs-material==9.5.39
      - mkdocs-mermaid2-plugin==1.1.1
      - mkdocstrings==0.26.1
      - mkdocstrings-python==1.11.1
      - pandera==0.20.4
      - projectcard>=0.3.3
